### ISSUE TITLE
linux build issue

### ISSUE THREAD

**Issue by rcon420** [Wend4r/mms-server_steam_account#2]
Hi its giving [01] Error in the meta list on linux. Do you have any idea why its happening?

**Comment by Wend4r** [comment]
Type `meta load server_steam_account` and send a output here

**Comment by alincupunct** [comment]
For me it was 
Failed to load plugin addons/server_steam_account/bin/linuxsteamrt64/server_steam_account (/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /home/container/game/csgo/addons/server_steam_account/bin/linuxsteamrt64/server_steam_account.so)).

We're running GLIBC 2.36 on Debian 12.

**Comment by Wend4r** [comment]
Try https://github.com/Wend4r/mms-server_steam_account/releases/download/1.0.0/server_steam_account-1.0.0-linux-low_glibc.zip

**Comment by rcon420** [comment]
> Try https://github.com/Wend4r/mms-server_steam_account/releases/download/1.0.0/server_steam_account-1.0.0-linux-low_glibc.zip

Hi this version solves issue. Loaded [03] Server Steam Account (1.0.0) by Wend4r
