### ISSUE TITLE
Plugin doesn't load after lastest update

### ISSUE THREAD

**Issue by alincupunct** [Wend4r/mms-server_steam_account#3]
Output is 
meta load server_steam_account
Failed to load plugin server_steam_account (File not found: /server_steam_account.so).

But the plugin is there (it also does the same thing with both your verison and the other metamod plugin version, only after the update from tonight).

**Comment by Wend4r** [comment]
Try to use 1225 and higher version of MM:Source - https://www.metamodsource.net/downloads.php?branch=dev

**Comment by daffyyyy** [comment]
Need to build with updated hl2sdk-cs2

**Comment by xlenonz** [comment]
need to update again Failed to get "SteamGameServer_Init" signature

**Comment by Wend4r** [comment]
Valve added a native `sv_setsteamaccount` after today update - https://github.com/SteamDatabase/GameTracking-CS2/commit/1393ff50351b12f8a53e9810376820b307542056#diff-16883f581bf0cd8e37006c5f3a69ffbefec83bd467e8ecff397ee377eb52999cR10359
There is no need for MM:S plugin anymore.
I will archive the repository
